apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinshome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 20000Mi
  volumeName: jenkinshome
