apiVersion: v1
data:
  jenkins-admin-password: djBXUUJuWkhHcQ==
  jenkins-admin-user: YWRtaW4=
kind: Secret
metadata:
  labels:
    app: my-jenkins
    release: my-jenkins
  name: my-jenkins
  namespace: default
type: Opaque
